"""Portable, evidence-preserving contracts for Soramimic Score."""

from .alignment import ObservedSingingUnit, build_known_lyrics_document
from .models import ModelConfig
from .phonetic_fallback import PhoneticMora
from .lyrics import LyricAdjustment, adjust_known_lyrics
from .surface import SurfaceLine, align_lyric_surface, attach_lyric_surface, lyric_surface, plan_lyric_inputs
from .audio import (
    AlignedMora,
    AudioAdapters,
    AudioPipelineError,
    LyricLine,
    MelodyNote,
    ReadingSelection,
    analyze_audio,
    build_audio_observations,
)
from .correspondence import (
    CorrespondenceAlternative,
    CorrespondenceConfig,
    CorrespondenceResult,
    align_correspondence,
    boundaryless_correspondence_config,
)
from .document import (
    FORMAT_NAME,
    SCHEMA_VERSION,
    ScoreDocument,
    compile_score,
    dump,
    dumps,
    from_linked_observations,
    load,
    loads,
)
from .ir import (
    Boundary,
    Evidence,
    IntermediateRepresentation,
    Link,
    LinkCost,
    Mora,
    NoteCandidate,
    Phoneme,
    Reading,
    SingingUnit,
    Utterance,
    ValidationError,
    VowelNucleus,
)
from .japanese import (
    LyricSpan,
    ReadingCandidate,
    kana_to_moras,
    kana_to_syllables,
    mora_distance,
    phonemes_for_mora,
    spans_from_ruby_text,
)
from .note_runs import (
    NoteOnlySpan,
    NoteRunAssignment,
    NoteRunConfig,
    NoteRunCost,
    NoteRunResult,
    PreservedNote,
    optimize_note_runs,
)
from .vocalization import (
    VocalizationExpansion,
    VocalizationReattack,
    expand_repeated_vocalizations,
)

__all__ = [
    "SurfaceLine",
    "align_lyric_surface",
    "attach_lyric_surface",
    "lyric_surface",
    "plan_lyric_inputs",
    "ModelConfig",
    "Boundary",
    "AlignedMora",
    "PhoneticMora",
    "AudioAdapters",
    "AudioPipelineError",
    "CorrespondenceAlternative",
    "CorrespondenceConfig",
    "CorrespondenceResult",
    "Evidence",
    "FORMAT_NAME",
    "IntermediateRepresentation",
    "Link",
    "LinkCost",
    "LyricSpan",
    "LyricLine",
    "LyricAdjustment",
    "Mora",
    "MelodyNote",
    "NoteCandidate",
    "NoteOnlySpan",
    "NoteRunAssignment",
    "NoteRunConfig",
    "NoteRunCost",
    "NoteRunResult",
    "ObservedSingingUnit",
    "Phoneme",
    "PreservedNote",
    "Reading",
    "ReadingCandidate",
    "ReadingSelection",
    "SCHEMA_VERSION",
    "ScoreDocument",
    "SingingUnit",
    "Utterance",
    "ValidationError",
    "VowelNucleus",
    "VocalizationExpansion",
    "VocalizationReattack",
    "align_correspondence",
    "adjust_known_lyrics",
    "analyze_audio",
    "boundaryless_correspondence_config",
    "build_known_lyrics_document",
    "build_audio_observations",
    "compile_score",
    "dump",
    "dumps",
    "expand_repeated_vocalizations",
    "from_linked_observations",
    "kana_to_moras",
    "kana_to_syllables",
    "mora_distance",
    "load",
    "loads",
    "optimize_note_runs",
    "phonemes_for_mora",
    "spans_from_ruby_text",
]
